### ISSUE TITLE
Midterm checkin - Vi

### ISSUE THREAD

**Issue by Vi-N-Tran** [dartmouth-cs98/classy-be#28]
Fav PR: 
- https://github.com/dartmouth-cs98/classy-be/commit/e3a006113aed3f1e78f8d76782f25fb7c83b346d
- why? I figured out how to upload to s3 when using typescript. This is not on cs52 tutorials and also not a lot of other tutorials have this exact stack so i was pretty proud when I figured this out.
<img width="791" alt="Screen Shot 2023-02-11 at 4 21 18 PM" src="https://user-images.githubusercontent.com/56491776/218355544-d74d18a0-c938-42e5-a685-59802d5b3068.png">

**Comment by timofei7** [comment]
looks like you all have node_modules in github, that's a bit of a anti-pattern, there should be no need to commit node_modules to github as that is a huge directory that is recreated from package.json by running `npm install` so  it is mostly just polluting the repo.
